### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by pubpub-zz** [ImoutoChan/ApngWpfPlayer#1]
Thanks for your good job I've been looking for a solution to extract frames from an apng framework for my project.
https://github.com/pubpub-zz/ppInk
I refactored it and its working great!
Before commiting, I need to confirm the License to consider for your project : can you add it. Thanks

**Comment by ImoutoChan** [comment]
Hi! Thanks, I've added the license. 
Have a good day!
