### ISSUE TITLE
我切换播放器的源，但是播放器依然播放旧的图像

### ISSUE THREAD

**Issue by ysdy44** [ImoutoChan/ApngWpfPlayer#3]
1. 我在应用程序里使用了播放器
2. 我给播放器的源设了第一个图像的路径
3. 播放器播放第一个图像
4. 我给播放器的源设了第二个图像的路径
5. 播放器依然播放第一个图像
但是我想让播放器播放第二个图像

**Comment by ImoutoChan** [comment]
I've published [new version](https://www.nuget.org/packages/ImoutoRebirth.ApngWpfPlayer/1.1.1) with the fix
