### ISSUE TITLE
用 ApngWpfPlayer 播放动图有残影，但用 Edge 浏览器播放正常

### ISSUE THREAD

**Issue by ysdy44** [ImoutoChan/ApngWpfPlayer#4]

**Comment by ImoutoChan** [comment]
https://www.nuget.org/packages/ImoutoRebirth.ApngWpfPlayer/1.1.2

**Comment by ysdy44** [comment]
速度好快（赞叹）
而且我试了试，残影也消失了

**Comment by ysdy44** [comment]
等一等，我发的这个这张动图是公司的资源，请不要放到开源项目里

**Comment by ysdy44** [comment]
你也许可以换成这张图，比如
![8cb63ccd71](https://user-images.githubusercontent.com/23761864/211500603-79c7b473-b120-44b3-ab56-edae92c65552.png)

**Comment by ImoutoChan** [comment]
You posted it publicly in this issue. But, sure, I removed it.

**Comment by ysdy44** [comment]
非常感谢，我也应该移除评论区的图像
