### ISSUE TITLE
AccessionViolationException occurred

### ISSUE THREAD

**Issue by SunnyDesignor** [ImoutoChan/ApngWpfPlayer#5]
When I played this image, an exception occurred, but it played well in Edge:
System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”

![1f4af (2)](https://github.com/ImoutoChan/ApngWpfPlayer/assets/50539661/e89c54bc-44aa-43b4-b4e1-ba521ade9624)

I converted the format using ffmpeg, it played successfully, but there were ghosts image.

![image](https://github.com/ImoutoChan/ApngWpfPlayer/assets/50539661/0b921ce6-f862-42c7-b09e-b57906b2c1d4)

**Comment by ImoutoChan** [comment]
I'll look into it

**Comment by ImoutoChan** [comment]
Should be fixed in [v1.4.1](https://www.nuget.org/packages/ImoutoRebirth.ApngWpfPlayer/1.4.1)

**Comment by SunnyDesignor** [comment]
Thank you, it’s playing well now
