### ISSUE TITLE
Edge defects appear during playing

### ISSUE THREAD

**Issue by SunnyDesignor** [ImoutoChan/ApngWpfPlayer#6]
Source file
![hourglass](https://github.com/ImoutoChan/ApngWpfPlayer/assets/50539661/e16f56af-bc4a-4d13-b9b6-91342db587d1)
Actual performance
![recording](https://github.com/ImoutoChan/ApngWpfPlayer/assets/50539661/72cbc8e7-1e01-4f66-b4ce-3b65a5714b81)

**Comment by ImoutoChan** [comment]
https://www.nuget.org/packages/ImoutoRebirth.ApngWpfPlayer/1.4.2

Should work as expected now
